games/urls.py
from django.urls import path

from . import views

app_name = 'games'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.CreateGame.as_view(), name='create_game'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/setup', views.setup_view, name='setup'),
    path('<int:pk>/main', views.open_main, name='main'),
    path('<int:pk>/end_game', views.end_game, name='end_game'),

    path('<int:pk>/ajax/status_gamers/', views.status_gamers, name='status_gamers'),
    path('<int:pk>/ajax/color_misterx/', views.color_misterx, name='color_misterx'),
    path('<int:pk>/ajax/test_city/', views.test_city, name='test_city'),
    path('<int:pk>/ajax/save_city/', views.save_city, name='save_city'),
    path('<int:pk>/ajax/setting_roles/', views.setting_roles, name='setting_roles'),
    path('<int:pk>/ajax/get_role/', views.get_role, name='get_role'),
    path('<int:pk>/ajax/change_queue/', views.change_queue, name='change_queue'),
    path('<int:pk>/ajax/test_queue/', views.test_queue, name='test_queue'),
    path('<int:pk>/ajax/add_step_of_misterx/', views.add_step_of_misterx, name='add_step_of_misterx'),
    path('<int:pk>/ajax/change_detectives_info/', views.change_detectives_info, name='change_detectives_info'),

    path('<int:pk>/ajax/get_steps_of_misterx/', views.get_steps_of_misterx, name='get_steps_of_misterx'),
    path('<int:pk>/ajax/get_tickets/', views.get_tickets, name='get_tickets'),
    path('<int:pk>/ajax/get_queue/', views.get_queue, name='get_queue'),
    path('<int:pk>/ajax/get_positions/', views.get_positions, name='get_positions'),
    path('<int:pk>/ajax/check_move_player/', views.check_move_player, name='check_move_player'),
    path('<int:pk>/ajax/remove_tickets/', views.remove_tickets, name='remove_tickets'),
    path('<int:pk>/ajax/complite_course/', views.complite_course, name='complite_course'),
    path('<int:pk>/ajax/get_evidences/', views.get_evidences, name='get_evidences'),
    path('<int:pk>/ajax/get_color_misterx/', views.get_color_misterx, name='get_color_misterx'),
    path('<int:pk>/ajax/check_end/', views.check_end, name='check_end'),
    path('<int:pk>/ajax/validate_double_step/', views.validate_double_step, name='validate_double_step'),
    path('<int:pk>/ajax/search_step/', views.search_step, name='search_step'),
    path('<int:pk>/ajax/validate_addition_step/', views.validate_addition_step, name='validate_addition_step'),
    path('<int:pk>/ajax/get_colors/', views.get_colors, name='get_colors'),
    path('<int:pk>/ajax/add_special_arts/', views.add_special_arts, name='add_special_arts'),
]

misterx/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('games/', include('games.urls')),
    path('accounts/profile/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
]

games/forms.py
from django import forms

from django.utils import timezone
from datetime import timedelta

from .models import Game


class CreateGameForm(forms.Form):
    game_name = forms.CharField()
    max_count_players = forms.IntegerField(initial=2)

    def save(self, form):
        cd = form.cleaned_data
        game = Game.objects.create(game_name=cd['game_name'],
                                   max_count_players=cd['max_count_players'],
                                   finish_date=timezone.now() + timedelta(hours=300),
                                   create_date=timezone.now()
                                   )
        game.save()

games/views.py
from random import randint
from itertools import product
import logging as log

from django.views import generic
from django.views.generic.edit import FormView
from django.shortcuts import render, get_object_or_404
from django.http import Http404, JsonResponse

from django.utils import timezone

from .models import Game, GamersInGame
from .forms import CreateGameForm
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from . import setting_game
from . import generation
from . import validate_action
from . import steps

log.basicConfig(
        level='INFO',
        format='%(name)s  %(levelname)s  %(filename)s  %(funcName)s  --> %(message)s',#  %(asctime)s
        filename='./misterx.log',
        filemode='a',
        )


@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView): #test
    template_name = 'games/index.html'
    context_object_name = 'game_list'

    def get_queryset(self):
        return Game.objects.filter(
                create_date__lte=timezone.now()).order_by('-create_date')


@method_decorator(login_required, name='dispatch')
class DetailView(generic.DetailView): #test
    model = Game
    template_name = 'games/detail.html'

    def get_queryset(self):
        return Game.objects.filter(
                create_date__lte=timezone.now()).order_by('-create_date')


@method_decorator(login_required, name='dispatch')
class CreateGame(FormView): #test
    form_class = CreateGameForm
    success_url = "/games/"
    template_name = "games/createGame.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        form.save(form)
        return super(CreateGame, self).form_valid(form)


@login_required
def open_main(request, pk, **kwargs):
    game = Game.objects.get(id=pk)
    if game.start_setting_status == False:
        game.initialization()

    context = {
            'game': game
            }
    return render(request, 'games/gameField.html', context)


@login_required
def end_game(request, pk, **kwargs):
    game = Game.objects.get(id=pk)
    win = {(True, False): 'misterx', (False, True): 'detectives', (True, True): 'detectives', (False, False): 'nobody'}[(validate_action.validate_win_misterx(game), validate_action.validate_win_detectives(game))]

    context = {
            'win': win,
            'city': game.get_cities['misterx']['white'],
            'game': game
            }
    return render(request, 'games/endGame.html', context)


@login_required
def setup_view(request, pk, **kwargs): #test
    template_name = "games/setupGamePage.html"
    game = get_object_or_404(Game, id=pk)
    if game.create_date <= timezone.now() <= game.finish_date:
        gamer = request.user
        game.add_gamer(gamer)
        return render(request,
                template_name=template_name,
                context={
                    'game': game,
                    'pk': pk,
                    'options': ['None', 'I-am-ready']
                    })
    else:
        raise Http404("Game does not exist")


@login_required
def status_gamers(request, pk, **kwargs):#+
    if request.method == 'GET':
        game = get_object_or_404(Game, pk=pk)
        data = {
                'players': [(lobby.gamer.id, lobby.ready, lobby.role, lobby.gamer==request.user)
                    for lobby in GamersInGame.objects.filter(game=pk)],
                'max_count': game.max_count_players
                }
        log.info(data)
        return JsonResponse(data)
    elif request.method == 'POST':
        gamer = request.user
        game = get_object_or_404(Game, pk=pk)
        ging = GamersInGame.objects.get(game=game, gamer=gamer)
        if request.POST.get('status', None) == "I-am-ready":
            ging.ready = True
            ging.save()
        if request.POST.get('status', None) == "Yes":
            ging.role = 'misterx'
            ging.save()
        data = {'success': True, 'role': ging.role, 'ready': ging.ready}
        log.info(data)
        return JsonResponse(data)
    raise Http404


@login_required
def color_misterx(request, pk, **kwargs):
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=pk)
        gamer = request.user
        ging = GamersInGame.objects.get(game=game, gamer=gamer)
        ging.color_misterx = request.POST.get('color', None)
        ging.save()

        data = {'success': True, 'color_misterx': ging.color_misterx}
        log.info(data)
        return JsonResponse(data)
    raise Http404


@login_required
def setting_roles(request, pk, **kwargs): # Perhaps, I can delete it. setting_games has the best analog
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=pk)
        if game.count_gamers_misterx == 0:
            misterx = randint(0, game.count_gamers-1)
            for i, gamer in enumerate(game.gamers.all()):
                ging = GamersInGame.objects.get(game=game, gamer=gamer)
                if i == misterx:
                    ging.role = 'misterx'
                    ging.save()
                else:
                    ging.role = 'detectives'
                    ging.save()
            log.info(ging)
        elif game.count_gamers_misterx >= 2:
            misterx = randint(0, game.count_gamers_misterx-1)
            players = [player for player in game.gamers.all()
                    if GamersInGame.objects.get(game=game, gamer=player).role_misterx == True]
            for i, gamer in enumerate(players):
                ging = GamersInGame.objects.get(game=game, gamer=gamer)
                if i == misterx:
                    ging.role = 'misterx'
                    ging.save()
                else:
                    ging.role = 'detectives'
                    ging.save()
            log.info(ging)
        data = {'success': True}
        return JsonResponse(data)
    raise Http404


@login_required
def test_city(request, pk, **kwargs): # This code need to correct and update ????
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=pk)
        user = request.user
        city = request.POST.get('city', None)
        ging = GamersInGame.objects.get(game=game, gamer=user)
        cities = game.get_cities
        if ging.role == 'misterx':
            if city in list(cities['detectives'].values()):
                data = {'result': 'false', 'city': city}
                # Мистер Х прoиграл
                print('------------------END------------------')
            else:
                data = {'result': 'true'}
        else:
            if city in list(cities['misterx'].values()):
                data = {'result': 'false', 'city': city}
                # ход невозможен
            else:
                data = {'result': 'true'}
                #color = request.POST.get('color')
                #game.change_cities(color=color, city=city, role='detectives')
        log.info(data)
        return JsonResponse(data)
    raise Http404


@login_required
def get_role(request, pk, **kwards): #test
    if request.method == 'GET':
        game = get_object_or_404(Game, pk=pk)
        gamer = request.user
        ging = GamersInGame.objects.get(game=game, gamer=gamer)
        role = ging.role
        data = {'role': role}
        log.info(data)
        return JsonResponse(data)
    raise Http404


@login_required
def save_city(request, pk, **kwards):
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=pk)
        color = request.POST.get('color', None)
        city = request.POST.get('city', None)
        user = request.user
        ging = GamersInGame.objects.get(game=game, gamer=user)

        role = ging.role # I deleted the part of code because it is unnecessary now
        game.change_city(color=color, city=city, role=role)
        data = {'color':color, 'city':city, 'role': role}
        log.info(data)
        return JsonResponse(data)
    raise Http404


@login_required
def change_queue(request, pk, **kwargs):
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=pk)
        user = request.user
        ging = GamersInGame.objects.get(game=game, gamer=user)
        role = ging.role

        game.change_queue(role);
        log.info(msg='Change_queue, new_queue: '+str(role))
        data = {'result':'true', 'role': role}
        return JsonResponse(data)
    raise Http404


@login_required
def test_queue(request, pk, **kwargs):
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=pk)
        user = request.user
        queue = game.queue
        ging = GamersInGame.objects.get(game=game, gamer=user)
        role = ging.role

        data = {'queue': queue}
        if role == queue:
            data['result'] = 'true'
        else:
            data['result'] = 'false'
        log.info(msg='Test_queue, data: ' + str(data))
        return JsonResponse(data)
    raise Http404

@login_required
def add_step_of_misterx(request, pk, **kwargs):
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=pk)
        new_step = request.POST.get('newStep', None)
        game.add_step_of_misterx(new_step)
        game.save()
        data = {'result':'true', 'steps': game.get_steps_of_misterx, 'count': game.count_steps}
        return JsonResponse(data)
    raise Http404

@login_required
def change_detectives_info(request, pk, **kwargs):
    if request.method == 'GET':
        game = get_object_or_404(Game, pk=pk)
        cities = game.get_cities['detectives']

templates/games/createGame.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'global_style/nav_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'global_style/global_style.css' %}" />
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
    <ul class="navbar">
        <li class="navbar"><a href="/">Home</a></li>
        <li class="navbar"><a class="active" href="/games">Games</a></li>
        <li class="navbar"><a href="/accounts/profile">Profile</a></li>
        <li class="navbar"><a href="/accounts/logout">Log out</a></li>
    </ul>
    <div id="container">
        <h3>New game</h3>
        <form action="" method="post">
            {% csrf_token %}
            <div class="second_div">
                <div>
                    <p>
		    	Game name:<br>
		    	{{form.game_name}}
		    </p>
		    <p>
		    	Numbers of players:<br>
		    	{{form.max_count_players}}
		    </p>
                </div>
                <hr>
            </div>

            <button type="submit">Create game</button>
            <button type="reset">Reset</button>
        </form>
    </div>
</body>
</html>

templates/games/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail of game</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'global_style/nav_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'global_style/global_style.css' %}" />
</head>
<body>
    <h1>Detail of game</h1>
    <ul class="navbar">
        <li class="navbar"><a href="/">Home</a></li>
        <li class="navbar"><a class="active" href="/games">Games</a></li>
        <li class="navbar"><a href="/accounts/profile">Profile</a></li>
        <li class="navbar"><a href="/accounts/logout">Log out</a></li>
    </ul>
    <div id="container">
	<h1>{{game.game_name}}</h1>
        <p>Date created: {{game.create_date}}</p>
        <p>Date finished: {{game.finish_date}}</p>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <p>Number of gamers: {{game.count_gamers}}</p>
	<p>Maximum of gamers: {{game.max_count_players}}</p>
        <hr>
        {% if game.can_gamers_add == True or request.user in game.gamers.all %}
            <a href="{% url 'games:setup' game.id %}">Take part</a>
        {% else %}
            <p>You will not be added to this game. </p>
        {% endif %}

    </div>
</body>
</html>

templates/games/endGame.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>End of game</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'global_style/nav_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'global_style/global_style.css' %}" />
</head>
<body>
    <h1>End of game</h1>
    <ul class="navbar">
        <li class="navbar"><a href="/">Home</a></li>
        <li class="navbar"><a class="active" href="/games">Games</a></li>
        <li class="navbar"><a href="/accounts/profile">Profile</a></li>
        <li class="navbar"><a href="/accounts/logout">Log out</a></li>
    </ul>
    <div id="container">
        <h1>{{ game.game_name }}</h1>
        <p>This game finished<p>
        <h3>Win: {{ win }}</h3>
        <p>MisterX is in {{ city }}</p>
    </div>
</body>
</html>

templates/games/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Games</title>
    <link rel="stylesheet" type="text/css" href="{% static 'global_style/nav_style.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'global_style/global_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'games/style_index.css' %}">
<body>
    <h1>Games</h1>
    <ul class="navbar">
        <li class="navbar"><a href="/">Home</a></li>
        <li class="navbar"><a class="active" href="/games">Games</a></li>
        <li class="navbar"><a href="/accounts/profile">Profile</a></li>
        <li class="navbar"><a href="/accounts/logout">Log out</a></li>
    </ul>
    <div id="container">
        <h3>Games</h3>
        <hr>
        <table class="games">
            <tr><td class="games">
                <a class="games" id="create_game" href="{% url 'games:create_game' %}">Create game</a>
            </td></tr>
        </table>
        <hr>
        {% if game_list %}
            <table class="games">
            {% for game in game_list %}
                <tr>
                    <td class="games">
                        <a href="{% url 'games:detail' game.id %}">{{ game.game_name }}</a>
                    </td>
                    <td class="games">
                        {% if game.can_gamers_add == True %}
                            <div class="status_game">..</div>
                        {% else %}
                            <div class="status_game">f</div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>No games are available.</p>
        {% endif %}

    </div>
</body>
</html>

templates/games/setupGamePage.html
<!DOCTYPE html>
<html lang="en">
    <head>
	{% load static %}
	<meta charset="UTF-8">
	<title>Setup game</title>
	{% block stylesheet %}
	<link rel="stylesheet" type="text/css" href="{% static 'global_style/nav_style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'global_style/global_style.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'games/style_setup.css' %}">
	{% endblock %}
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	{% csrf_token %}

    </head>
    <body>
	<ul class="navbar">
	    <li class="navbar"><a href="/">Home</a></li>
	    <li class="navbar"><a class="active" href="/games">Games</a></li>
	    <li class="navbar"><a href="/accounts/profile">Profile</a></li>
	    <li class="navbar"><a href="/accounts/logout">Log out</a></li>
	</ul>
	<div id="container">
	    <h1>{{ game.game_name }}</h1>
	    <hr>
	    <div id="tableRole" class="second_div">
		<p>You are <i style="color: #4CAF50">{{request.user}}</i>.</p>
		<p id="thColor" hidden><b>Color of Mr.X cities:</b>
		<select id='color_misterx'>
		    <option id='green'>green</option>
		    <option id='yellow'>yellow</option>
		    <option id='orange'>orange</option>
		</select></p>

		<div class="third_div">
		    <table class="gamers">
			<tr>
			    <th>Gamer</th><th>Status</th><th>Desire to be Mr.X</th>
			</tr>
			{% for gamer in game.gamers.all %}
			<tr>
			    <td class="gamers">{{gamer}}</td>
			    <td id="gamer{{gamer.id}}" class="status">
				{% if gamer == request.user %}
				<select id="in_status">
				    {% for opt in options %}
				    <option id="{{ opt }}">{{ opt }}</option>
				    {% endfor %}
				</select>
				{% else %}
				<i>Not ready</i>
				{% endif %}
			    </td>
			    <td id="misterx{{gamer.id}}" class="misterx">
				{% if gamer == request.user %}
				<select id="in_want">
				    <option id="No">No</option>
				    <option id="Yes">Yes</option>
				</select>
				{% else %}
				<i>No</i>
				{% endif %}
			    </td>
			</tr>
			
			{% endfor %}
		    </table>
		</div>
	    </div>
	    <hr>
	    <div class="chat" class="second_div" style="display:none">
		<input class='chat' type="text" id="input_text">
		<input type="button" value="Send">
		<p class="chat">---</p>
	    </div>
	</div>
	{% block javascript %}
	<script>
$(function (){
    var gamer_id = {{request.user.id}};
    var csrftoken = $("[name=csrfmiddlewaretoken]").val();
    function csrfSafeMethod(method) {
	// these HTTP methods do not require CSRF protection
	return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
	beforeSend: function(xhr, settings) {
	    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
		xhr.setRequestHeader("X-CSRFToken", csrftoken);
	    }
	}
    });

    

    function poll() {
	$.get('ajax/status_gamers/', function(data){
	    var countReady = 0;
	    for(player of data.players) {
		if(player[1]) {
		    console.info('#gamer' + player[0]);
		    $('#gamer' + player[0]).html('<b>Ready!</b>');
		    countReady += 1;
		}
		if(player[2] == "misterx") {
		    console.info('#misterx' + player[0]);
		    $('#misterx' + player[0]).html('<b>Yes</b>');
		    
		    if (player[3] == true){
		    	document.getElementById("thColor").hidden = false;
		    }
		}
	    }
	    if (data.max_count == countReady){
		window.location.href = "{% url 'games:main' game.id %}";
	    }
	    else {
		setTimeout(poll, 5000);
	    }
	   

	});
    };
    poll();

    $("#in_status").on('change', function () {
	var status = $(this).val();
	$.post({
	    url: 'ajax/status_gamers/',
	    data: {
		'status': status,
	    },
	    dataType: 'json',
	    success:
	    function (data) {
		console.info('Success send status ready', data);
	    }
	});
    });
    $("#in_want").on('change', function () {
	var status = $(this).val();
	$.post({
	    url: 'ajax/status_gamers/',
	    data: {
		'status': status,
	    },
	    dataType: 'json',
	    success:
	    function (data) {
		console.info("Success send status MX", data);
		if (data["role"] == true){
		    document.getElementById("thColor").hidden = false;
		}
		else {
		    $("#thColor").hidden = true;
		}
	    }
	});
    });
    $("#color_misterx").on('change', function () {
	var color = $(this).val();
	console.log(color);
	$.post({
	    url: 'ajax/color_misterx/',
	    data: {
		'color': color,
	    },
	    dataType: 'json',
	    success:
	    function (data) {
		console.info('Success send color MX', data);
	    }
	});
    });
});
	</script>
	{% endblock %}
    </body>
</html>